version: 2
updates:
  # Maintain dependencies for Cargo
  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: monthly
    open-pull-requests-limit: 10
    groups:
      minor:
        update-types:
          - "minor"
      patch:
        update-types:
          - "patch"

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
    open-pull-requests-limit: 10
    groups:
      minor:
        update-types:
          - "minor"
      patch:
        update-types:
          - "patch"

  # Maintain dependencies for NPM
  - package-ecosystem: "npm"
    directory: "/website"
    schedule:
      interval: monthly
    open-pull-requests-limit: 10
    groups:
      minor:
        update-types:
          - "minor"
      patch:
        update-types:
          - "patch"

  - package-ecosystem: npm
    directory: /npm/git-cliff
    schedule:
      interval: monthly
    open-pull-requests-limit: 10
    groups:
      minor:
        update-types:
          - "minor"
      patch:
        update-types:
          - "patch"
    ignore:
      # We intentionally ignore semver-major updates to avoid
      # PR noise when new Node versions are released.
      # Revisit this when updating the supported Node.js range.
      - dependency-name: "@types/node"
        update-types: ["version-update:semver-major"]

  # Maintain dependencies for Docker
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 10
